matrix:
- name: Python Source
  aspell:
    lang: pl
    d: pl
  sources:
  - assets/**/*rst
  - assets/**/*md
  dictionary:
    wordlists:
    - assets/custom-wordlist.txt
    - assets/excluding.txt
    - assets/roma_numbers.txt
    output: _build/dictionary/python.dic
    encoding: utf-8

