name: Pages
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Update modification date and commit info
      run: make modify-date
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        extra_files: |
          CNAME
          LICENSE
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
